language: node_js
sudo: false
git:
  depth: 10

os:
  - windows
  - linux

node_js:
  - '8'
  - '10'
  - '12'

install:
  - yarn version
  - yarn global codecov
  - yarn install

script:
  - yarn test

after_success:
  - codecov

# safelist (prevent double builds in PRs)
branches:
  only:
    - master
    - /^greenkeeper.*$/

